### ISSUE TITLE
Can't open Firefox

### ISSUE THREAD

**Issue by BlackLordDSNR** [RandomCoderOrg/ubuntu-on-android#193]
Hello. Today I installed Ubuntu using hippo. The system started without problems, I connected to the VNC server. I tried to open the browser, and then the problems started. First, I can't find any browser. When I click on the "Web Browser" button in the menu, I get an error. Firefox is installed and is the default browser. Also after the first restart, the top bar disappeared for me, but this is not a problem. Please tell me how can I start the browser?
![Screenshot_20220905_144948](https://user-images.githubusercontent.com/88499005/188443495-2ceb7ac2-cd76-4d8c-a0fb-965284537bbc.jpg)
![Screenshot_20220905_144859](https://user-images.githubusercontent.com/88499005/188443497-fb73f58a-56e8-4f20-b9be-0a73958b822a.jpg)
![Screenshot_20220905_144826](https://user-images.githubusercontent.com/88499005/188443499-e0fbffc8-83bf-4863-a3d7-7cce8d3ca198.jpg)

**Comment by AnninoDr4** [comment]
Looks like new firefox snap decision from ubuntu is finally in motion
> Expect to get fixed soon

**Comment by BlackLordDSNR** [comment]
I tried to install Firefox using Snap, but...

snap install firefox
error: cannot communicate with server: Post "http://localhost/v2/snaps/firefox": dial unix /run/snapd.socket: connect: no such file or directory

**Comment by BlackLordDSNR** [comment]
Maybe I did something wrong, I don't know.

**Comment by AnninoDr4** [comment]
> Maybe I did something wrong, I don't know.

NO

**Comment by AnninoDr4** [comment]
@BlackLordDSNR Use this command in udroid. you can use firefox again normally
```bash
bash < <(curl -s https://raw.githubusercontent.com/RandomCoderOrg/udroid-app-ports/main/firefox/install.sh)
```

<hr>

fixed in https://github.com/RandomCoderOrg/udroid-app-ports/commit/1cd1bc4fe94fb01fdaa868564a6d8de43e0ecece & https://github.com/RandomCoderOrg/udroid-app-ports/commit/c3d1c51d946b59dd80e01968602ce1e4fd8e5713

**Comment by SinouDev** [comment]
Still having the same issue even after using the script.

![Screenshot_20220920-180514_XServer XSDL](https://user-images.githubusercontent.com/52191094/191320686-31f2218a-0f73-4b6a-90c9-d3d896a9daa3.jpg)

**Comment by Ash-ketchm** [comment]
[backup.tar.gz](https://github.com/RandomCoderOrg/ubuntu-on-android/files/9686573/backup.tar.gz)

Do the following command
```
tar -xvf /sdcard/Download/backup.tar.gz -C /sdcard/Download
```
```
export deps = "gir1.2-packagekitglib-1.0 libappstream4 libdw1 libglib2.0-bin
  libgstreamer1.0-0 libpackagekit-glib2-18 libpolkit-agent-1-0          libpolkit-gobject-1-0 libstemmer0d libunwind8 libxmlb2 packagekit
  packagekit-tools pkexec policykit-1 polkitd python3-blinker           python3-cffi-backend python3-cryptography python3-distro
  python3-distro-info python3-httplib2 python3-importlib-metadata       python3-jeepney python3-jwt python3-keyring python3-launchpadlib
  python3-lazr.restfulclient python3-lazr.uri python3-more-itertools    python3-oauthlib python3-pyparsing python3-secretstorage
  python3-six python3-software-properties python3-wadllib               python3-zipp software-properties-common unattended-upgrades"
```
```
cp /sdcard/Download/mozillateam-ubuntu-ppa-jammy.list /etc/apt/sources.list.d
cp /sdcard/Download/mozillateam-ubuntu-ppa.gp* /etc/apt/trusted.gpg.d
sudo apt update
sudo apt install $deps -y
sudo apt purge firefox -y
sudo apt install ffmpeg firefox firefox-locale-en -y
```


# This work for me

**Comment by Ash-ketchm** [comment]
> Do the following command
> 
> ```
> export deps = "gir1.2-packagekitglib-1.0 libappstream4 libdw1 libglib2.0-bin
>   libgstreamer1.0-0 libpackagekit-glib2-18 libpolkit-agent-1-0          libpolkit-gobject-1-0 libstemmer0d libunwind8 libxmlb2 packagekit
>   packagekit-tools pkexec policykit-1 polkitd python3-blinker           python3-cffi-backend python3-cryptography python3-distro
>   python3-distro-info python3-httplib2 python3-importlib-metadata       python3-jeepney python3-jwt python3-keyring python3-launchpadlib
>   python3-lazr.restfulclient python3-lazr.uri python3-more-itertools    python3-oauthlib python3-pyparsing python3-secretstorage
>   python3-six python3-software-properties python3-wadllib               python3-zipp software-properties-common unattended-upgrades"
> ```
> 
> ```
> cp /sdcard/Download/mozillateam-ubuntu-ppa-jammy.list /etc/apt/sources.list.d
> cp /sdcard/Download/mozillateam-ubuntu-ppa.gp* /etc/apt/trusted.gpg.d
> sudo apt update
> sudo apt install $deps -y
> sudo apt purge firefox -y
> sudo apt install ffmpeg firefox firefox-locale-en -y```
> 
> 
> # This work for me
> ```



> Hello. Today I installed Ubuntu using hippo. The system started without problems, I connected to the VNC server. I tried to open the browser, and then the problems started. First, I can't find any browser. When I click on the "Web Browser" button in the menu, I get an error. Firefox is installed and is the default browser. Also after the first restart, the top bar disappeared for me, but this is not a problem. Please tell me how can I start the browser? ![Screenshot_20220905_144948](https://user-images.githubusercontent.com/88499005/188443495-2ceb7ac2-cd76-4d8c-a0fb-965284537bbc.jpg) ![Screenshot_20220905_144859](https://user-images.githubusercontent.com/88499005/188443497-fb73f58a-56e8-4f20-b9be-0a73958b822a.jpg) ![Screenshot_20220905_144826](https://user-images.githubusercontent.com/88499005/188443499-e0fbffc8-83bf-4863-a3d7-7cce8d3ca198.jpg)

**Comment by ask9027** [comment]
> Hello. Today I installed Ubuntu using hippo. The system started without problems, I connected to the VNC server. I tried to open the browser, and then the problems started. First, I can't find any browser. When I click on the "Web Browser" button in the menu, I get an error. Firefox is installed and is the default browser. Also after the first restart, the top bar disappeared for me, but this is not a problem. Please tell me how can I start the browser? ![Screenshot_20220905_144948](https://user-images.githubusercontent.com/88499005/188443495-2ceb7ac2-cd76-4d8c-a0fb-965284537bbc.jpg) ![Screenshot_20220905_144859](https://user-images.githubusercontent.com/88499005/188443497-fb73f58a-56e8-4f20-b9be-0a73958b822a.jpg) ![Screenshot_20220905_144826](https://user-images.githubusercontent.com/88499005/188443499-e0fbffc8-83bf-4863-a3d7-7cce8d3ca198.jpg)

Just type `firefox` not `firefoz`
there is a typing error
